export const IS_ENABLE = 'is_open'
export const DOWNLOAD_CLIENT_URL = 'download_client'
export const DOWNLOAD_CLIENT_TYPE = 'download_client_type'
export const DOWNLOAD_SAVEPATH = 'download_client_savePath'
export const BOOK_MARK_TORRENTS = 'book_mark_torrents'
export const REMOVE_WATERMARK = 'remove_watermark'
